name: Parallel Test Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  push:
    branches: [main]

jobs:
  Login-Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          STANDARD_USER_USERNAME: ${{ env.STANDARD_USER_USERNAME }} 
          STANDARD_USER_PASSWORD: ${{ env.STANDARD_USER_PASSWORD }} 
        with:
          command: npm run test:Login
  Products-Test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          STANDARD_USER_USERNAME: ${{ env.STANDARD_USER_USERNAME }} # Access loaded env var
          STANDARD_USER_PASSWORD: ${{ env.STANDARD_USER_PASSWORD }} # Access loaded env var
        with:
          command: npm run test:Products